name: flutter_progress_hud
description: Highly customizable modal progress indicator with fade animation.
version: 2.0.0
homepage: https://github.com/FlorinMihalache/flutter_progress_hud

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter